set -g mode-keys vi
set -g mouse on
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe
bind-key O select-pane -t :.+ \; resize-pane -Z
bind-key Z resize-pane -Z \; select-pane -t :.+ 

